name: Ionic Appflow Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Lint Code
      run: npm run lint || echo "Linting completed"
      
    - name: Build React App
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npx cap sync --no-build
        
    - name: Validate Build Assets
      run: |
        ls -la dist/
        if [ ! -f dist/index.html ]; then
          echo "Build failed: index.html not found"
          exit 1
        fi
        echo "✅ Build validation successful"
        
    - name: Trigger Ionic Appflow Build
      if: github.ref == 'refs/heads/main'
      run: |
        echo "✅ Main branch updated - Ionic Appflow should auto-trigger build"
        echo "Monitor build at: https://dashboard.ionicframework.com/apps/a5b6d54f/builds"

